slack:
  token: "xbc8d-15241568911-246524567892-345678912836-h2ja25gdnqaj23g671cja56bvxv40ggg"
  webhook: "None"
  channel: "alerts"
  username: "PyAlerts"

config:
  timeout: 60
  percent_threshold:
    cpu_threshold: 90
    ram_threshold: 90
    disk_threshold: 90

