slack:
  token: "xoxp-99064668098-101064058484-324461180432-a3fa99efcade60a442bfa90a8ee16bcb"
  webhook: "None"
  channel: "alerts"
  username: "PyAlerts"

config:
  timeout: 60
  percent_threshold:
    cpu_threshold: 90
    ram_threshold: 90
    disk_threshold: 90
