# Token replaced by git hook
slack:
  token: "xxxxxx-xxxx-xxxxxxx-xxxx-xxxxxxxxx"
  webhook: "None"
  channel: "alerts"
  username: "PyAlerts"

config:
  percent_threshold:
    cpu_threshold: 90
    ram_threshold: 90
    disk_threshold: 90

alerts:
  timeout: 30

master:
  ports:
    zmq: 5151

drone:
  ports:
    zmq: 5252

redis:
  port: 6379
  ttl: 5000
  timeout: 60

#command:
#  cpu: "top -n 1 | awk 'NR == 3 {print}' | awk '{print $2}'"
