slack:
  token: "xxxxxx-xxxx-xxxxxxx-xxxx-xxxxxxxxx"
  webhook: "None"
  channel: "alerts"
  username: "PyAlerts"

config:
  timeout: 60
  percent_threshold:
    cpu_threshold: 90
    ram_threshold: 90
    disk_threshold: 90

